# Data Visualisation of Recursive Retrieval

In [38]:
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.ticker import LogLocator

from pathlib import Path
import pandas as pd
import sys

sys.path.append("..")
import visualization

%matplotlib inline
%config InlineBackend.figure_format = 'pdf'

In [39]:
# Load data from files
path = Path("202506070756/")
path2 = Path("202506081353/")
df1 = pd.read_csv(path / Path("results-qa1.csv"))
df1["QA"] = "QA1"

df2 = pd.read_csv(path / Path("results-qa2.csv"))
df2["QA"] = "QA2"

df3 = pd.read_csv(path / Path("results-qa3.csv"))
df3["QA"] = "QA3"

df4 = pd.read_csv(path / Path("results-qa4.csv"))
df4["QA"] = "QA4"

df5 = pd.read_csv(path / Path("results-qa5.csv"))
df5["QA"] = "QA5"

df6 = pd.read_csv(path2 / Path("results-qa1.csv"))
df6["QA"] = "QA1"

df7 = pd.read_csv(path2 / Path("results-qa2.csv"))
df7["QA"] = "QA2"

df8 = pd.read_csv(path2 / Path("results-qa3.csv"))
df8["QA"] = "QA3"

df9 = pd.read_csv(path2 / Path("results-qa4.csv"))
df9["QA"] = "QA4"

df10 = pd.read_csv(path2 / Path("results-qa5.csv"))
df10["QA"] = "QA5"


rr_df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10])
rr_df

,token_size,index,question,target,actual,correct_guess,process_time,answer_time,total_llm_time,total_input_tokens,total_output_tokens,QA
0,0,1,Where is Daniel?,bathroom,Bathroom,True,0.878757,5.868878,2.897825,404,13,QA1
1,0,2,Where is Daniel?,bedroom,Kitchen,False,0.123031,17.656334,3.947092,692,101,QA1
2,0,3,Where is Daniel?,bathroom,Office,False,0.120000,95.382631,2.642015,587,42,QA1
3,0,4,Where is Sandra?,garden,Garden,True,0.121126,124.407568,4.611865,923,111,QA1
4,0,5,Where is Sandra?,bathroom,Bathroom,True,0.115664,90.023576,5.057877,1004,143,QA1
...,...,...,...,...,...,...,...,...,...,...,...,...
175,16,46,Who received the football?,Fred,Fred,True,2.840683,35.006036,48.809569,11398,3537,QA5
176,16,47,Who gave the football to Jeff?,Mary,Mary,True,2.949033,59.567752,96.834513,23250,7271,QA5
177,16,48,Who did Jeff give the football to?,Fred,Fred,True,3.021359,96.680598,237.674161,69941,23921,QA5
178,16,49,Who did Jeff give the football to?,Bill,Bill,True,2.991833,191.874525,194.900077,48961,22625,QA5
179,16,50,What did Bill give to Mary?,apple,Apple,True,2.167702,89.963002,123.728725,32695,12962,QA5

In [40]:
accuracy_df = rr_df.groupby(['QA', 'token_size'])['correct_guess'].mean().reset_index()
accuracy_df

     QA  token_size  correct_guess
0   QA1           0           0.84
1   QA1           1           0.46
2   QA1           2           0.36
3   QA1           4           0.40
4   QA1           8           0.46
5   QA1          16           0.32
6   QA2           0           0.58
7   QA2           1           0.34
8   QA2           2           0.04
9   QA2           4           0.14
10  QA2           8           0.00
11  QA2          16           0.08
12  QA3           0           0.14
13  QA3           1           0.20
14  QA3           2           0.16
15  QA3           4           0.18
16  QA3           8           0.06
17  QA3          16           0.10
18  QA4           0           0.84
19  QA4           1           0.54
20  QA4           2           0.62
21  QA4           4           0.72
22  QA4           8           0.56
23  QA4          16           0.58
24  QA5           0           0.84
25  QA5           1           0.70
26  QA5           2           0.68
27  QA5           4           0.68
28  QA5           8           0.70
29  QA5          16           0.62

In [41]:
visualization.create_heatmap(accuracy_df, "Recursive Retrieval Accuracy", index_type='QA')

In [42]:
visualization.create_line_chart(accuracy_df,
                                experiment_title='Recursive Retrieval Accuracy',
                                category='QA',
                                x_lims=(0, 18))

### ReES Truncated Accuracy Chart

In [43]:
rees_dataset_path = Path("../main-accuracy/202506052215")
rees_dataset_path2 = Path("../main-accuracy/202506081025")
rees_dataset_path3 = Path("../main-accuracy/202506081359")

df1 = pd.read_csv(rees_dataset_path / Path("results-qa1.csv"))
df1["QA"] = "QA1"

df2 = pd.read_csv(rees_dataset_path / Path("results-qa2.csv"))
df2["QA"] = "QA2"

df3 = pd.read_csv(rees_dataset_path / Path("results-qa3.csv"))
df3["QA"] = "QA3"

df4 = pd.read_csv(rees_dataset_path / Path("results-qa4.csv"))
df4["QA"] = "QA4"

df5 = pd.read_csv(rees_dataset_path / Path("results-qa5.csv"))
df5["QA"] = "QA5"

df6 = pd.read_csv(rees_dataset_path2 / Path("results-qa1.csv"))
df6["QA"] = "QA1"

df7 = pd.read_csv(rees_dataset_path2 / Path("results-qa2.csv"))
df7["QA"] = "QA2"

df8 = pd.read_csv(rees_dataset_path2 / Path("results-qa3.csv"))
df8["QA"] = "QA3"

df9 = pd.read_csv(rees_dataset_path2 / Path("results-qa4.csv"))
df9["QA"] = "QA4"

df10 = pd.read_csv(rees_dataset_path2 / Path("results-qa5.csv"))
df10["QA"] = "QA5"

df11 = pd.read_csv(rees_dataset_path3 / Path("results-qa1.csv"))
df11["QA"] = "QA1"

df12 = pd.read_csv(rees_dataset_path3 / Path("results-qa2.csv"))
df12["QA"] = "QA2"

df13 = pd.read_csv(rees_dataset_path3 / Path("results-qa3.csv"))
df13["QA"] = "QA3"

df14 = pd.read_csv(rees_dataset_path3 / Path("results-qa4.csv"))
df14["QA"] = "QA4"

df15 = pd.read_csv(rees_dataset_path3 / Path("results-qa5.csv"))
df15["QA"] = "QA5"


rees_df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15])
rees_df

,token_size,index,question,target,actual,correct_guess,process_time,answer_time,total_llm_time,total_input_tokens,total_output_tokens,QA
0,0,1,Where is Daniel?,bathroom,Bathroom,True,0.662705,4.502335,2.177853,237,7,QA1
1,0,2,Where is Daniel?,bedroom,Bedroom,True,0.141209,1.983102,1.406854,257,14,QA1
2,0,3,Where is Daniel?,bathroom,Office,False,0.117498,1.745565,1.408585,238,10,QA1
3,0,4,Where is Sandra?,garden,garden,True,0.104040,2.055796,1.392899,278,23,QA1
4,0,5,Where is Sandra?,bathroom,Bathroom,True,0.106141,1.725195,1.581132,284,17,QA1
...,...,...,...,...,...,...,...,...,...,...,...,...
175,128,46,What did Fred give to Jeff?,football,Football,True,27.230084,37.867511,62.769474,10042,3320,QA5
176,128,47,Who received the milk?,Fred,Fred,True,27.326057,10.057308,9.184162,1765,463,QA5
177,128,48,Who gave the football?,Fred,Unknown,False,26.333264,17.481851,16.015608,2891,910,QA5
178,128,49,Who gave the football?,Fred,Fred,True,26.911899,5.247260,4.518200,1482,77,QA5
179,128,50,Who gave the milk to Jeff?,Mary,Uncle,False,25.937744,8.473390,8.792185,1725,382,QA5

In [44]:
rees_df_16k = rees_df[rees_df['token_size'] <= 16]
rees_df_16k

,token_size,index,question,target,actual,correct_guess,process_time,answer_time,total_llm_time,total_input_tokens,total_output_tokens,QA
0,0,1,Where is Daniel?,bathroom,Bathroom,True,0.662705,4.502335,2.177853,237,7,QA1
1,0,2,Where is Daniel?,bedroom,Bedroom,True,0.141209,1.983102,1.406854,257,14,QA1
2,0,3,Where is Daniel?,bathroom,Office,False,0.117498,1.745565,1.408585,238,10,QA1
3,0,4,Where is Sandra?,garden,garden,True,0.104040,2.055796,1.392899,278,23,QA1
4,0,5,Where is Sandra?,bathroom,Bathroom,True,0.106141,1.725195,1.581132,284,17,QA1
...,...,...,...,...,...,...,...,...,...,...,...,...
115,16,46,Who received the football?,Fred,Fred,True,2.834731,18.370504,17.487607,1554,235,QA5
116,16,47,Who gave the football to Jeff?,Mary,Mary,True,2.962007,27.443735,30.433699,5115,1651,QA5
117,16,48,Who did Jeff give the football to?,Fred,Fred,True,3.025274,33.773022,42.186800,7722,2774,QA5
118,16,49,Who did Jeff give the football to?,Bill,Bill,True,2.979415,8.141092,9.436982,1599,290,QA5
119,16,50,What did Bill give to Mary?,apple,Apple,True,2.178206,32.709141,44.317474,6648,1856,QA5

In [45]:
rees_accuracy_df = rees_df_16k.groupby(['QA', 'token_size'])['correct_guess'].mean().reset_index()
rees_accuracy_df

     QA  token_size  correct_guess
0   QA1           0           0.82
1   QA1           1           0.54
2   QA1           2           0.50
3   QA1           4           0.36
4   QA1           8           0.34
5   QA1          16           0.38
6   QA2           0           0.50
7   QA2           1           0.18
8   QA2           2           0.04
9   QA2           4           0.02
10  QA2           8           0.00
11  QA2          16           0.00
12  QA3           0           0.22
13  QA3           1           0.24
14  QA3           2           0.08
15  QA3           4           0.10
16  QA3           8           0.06
17  QA3          16           0.04
18  QA4           0           0.78
19  QA4           1           0.52
20  QA4           2           0.52
21  QA4           4           0.68
22  QA4           8           0.56
23  QA4          16           0.58
24  QA5           0           0.78
25  QA5           1           0.60
26  QA5           2           0.64
27  QA5           4           0.56
28  QA5           8           0.64
29  QA5          16           0.68

In [46]:
visualization.create_line_chart(rees_accuracy_df,
                                experiment_title='Basic Retrieval Accuracy (up to 16k)',
                                category='QA',
                                x_lims=(0, 18))

In [47]:
visualization.create_heatmap(rees_accuracy_df, experiment_title='Basic Retrieval Accuracy (up to 16k)', index_type='QA')

## Data Visualisation of Recursive Retrieval Prompt Usage

In [48]:
# Load RR data from files
path = Path("202506070756/")
path2 = Path("202506081353/")

df1 = pd.read_csv(path / Path("prompts-qa1.csv"))
df1["QA"] = "QA1"

df2 = pd.read_csv(path / Path("prompts-qa2.csv"))
df2["QA"] = "QA2"

df3 = pd.read_csv(path / Path("prompts-qa3.csv"))
df3["QA"] = "QA3"

df4 = pd.read_csv(path / Path("prompts-qa4.csv"))
df4["QA"] = "QA4"

df5 = pd.read_csv(path / Path("prompts-qa5.csv"))
df5["QA"] = "QA5"

df6 = pd.read_csv(path2 / Path("prompts-qa1.csv"))
df6["QA"] = "QA1"

df7 = pd.read_csv(path2 / Path("prompts-qa2.csv"))
df7["QA"] = "QA2"

df8 = pd.read_csv(path2 / Path("prompts-qa3.csv"))
df8["QA"] = "QA3"

df9 = pd.read_csv(path2 / Path("prompts-qa4.csv"))
df9["QA"] = "QA4"

df10 = pd.read_csv(path2 / Path("prompts-qa5.csv"))
df10["QA"] = "QA5"


rr_df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10])
rr_df

,token_size,index,prompt,response,llm_time,input_tokens,output_tokens,entity,QA
0,0,1,<summary>\n\n</summary>\n<chunk>\nDaniel moved...,Daniel moved to the bathroom.,1.412632,161,6,daniel,QA1
1,0,1,<summary>\n\n</summary>\n<chunk>\nDaniel moved...,Daniel moved to the bathroom.,0.956846,161,6,bathroom,QA1
2,0,1,<summary>\nDaniel moved to the bathroom.\n\nDa...,Bathroom,0.528347,82,1,NaN,QA1
3,0,2,<summary>\n\n</summary>\n<chunk>\nDaniel moved...,Daniel moved to the kitchen and later journeye...,0.784679,174,13,daniel,QA1
4,0,2,<summary>\n\n</summary>\n<chunk>\nDaniel moved...,"The kitchen is a location where Daniel, Sandra...",1.757220,174,57,kitchen,QA1
...,...,...,...,...,...,...,...,...,...
6208,16,50,<summary>\nSir William Gordon of Park was a di...,Sir William Gordon of Park was a distinguished...,5.341851,3118,587,gordon,QA5
6209,16,50,<summary>\nSir William Gordon of Park was a di...,Sir William Gordon of Park was a distinguished...,4.236797,820,638,gordon,QA5
6210,16,50,<summary>\nSir William Gordon of Park was a di...,Sir William Gordon of Park was a distinguished...,4.759015,837,683,gordon,QA5
6211,16,50,<summary>\nSir William Gordon of Park was a di...,Sir William Gordon of Park was a distinguished...,4.543019,875,732,gordon,QA5
6212,16,50,<summary>\nBill is a protective and authoritat...,Apple,0.536038,1570,1,NaN,QA5

In [49]:
# Remove Answers, so we only have summaries left
rr_df = rr_df[rr_df['entity'].notna()]
rr_df

,token_size,index,prompt,response,llm_time,input_tokens,output_tokens,entity,QA
0,0,1,<summary>\n\n</summary>\n<chunk>\nDaniel moved...,Daniel moved to the bathroom.,1.412632,161,6,daniel,QA1
1,0,1,<summary>\n\n</summary>\n<chunk>\nDaniel moved...,Daniel moved to the bathroom.,0.956846,161,6,bathroom,QA1
3,0,2,<summary>\n\n</summary>\n<chunk>\nDaniel moved...,Daniel moved to the kitchen and later journeye...,0.784679,174,13,daniel,QA1
4,0,2,<summary>\n\n</summary>\n<chunk>\nDaniel moved...,"The kitchen is a location where Daniel, Sandra...",1.757220,174,57,kitchen,QA1
5,0,2,<summary>\n\n</summary>\n<chunk>\nDaniel moved...,The bedroom is a location that Daniel and Mary...,0.910382,174,30,bedroom,QA1
...,...,...,...,...,...,...,...,...,...
6207,16,50,<summary>\nSir William Gordon of Park was a di...,Sir William Gordon of Park was a distinguished...,3.971206,780,534,gordon,QA5
6208,16,50,<summary>\nSir William Gordon of Park was a di...,Sir William Gordon of Park was a distinguished...,5.341851,3118,587,gordon,QA5
6209,16,50,<summary>\nSir William Gordon of Park was a di...,Sir William Gordon of Park was a distinguished...,4.236797,820,638,gordon,QA5
6210,16,50,<summary>\nSir William Gordon of Park was a di...,Sir William Gordon of Park was a distinguished...,4.759015,837,683,gordon,QA5
6211,16,50,<summary>\nSir William Gordon of Park was a di...,Sir William Gordon of Park was a distinguished...,4.543019,875,732,gordon,QA5

In [50]:
# Group data by samples (texts and tokensize)
grouped_rr_df = rr_df.groupby(['token_size', 'index', 'QA'])['prompt'].count().reset_index()
grouped_rr_df

      token_size  index   QA  prompt
0              0      1  QA1       2
1              0      1  QA2       4
2              0      1  QA3      64
3              0      1  QA4       3
4              0      1  QA5       6
...          ...    ...  ...     ...
1391          16     50  QA1       2
1392          16     50  QA2      70
1393          16     50  QA3      26
1394          16     50  QA4       2
1395          16     50  QA5      69

[1396 rows x 4 columns]

In [51]:
# Mean data (want mean of prompts)
mean_rr_df = grouped_rr_df.groupby(['token_size', 'QA'])["prompt"].mean().reset_index()
mean_rr_df

    token_size   QA     prompt
0            0  QA1   3.200000
1            0  QA2   4.265306
2            0  QA3  26.540000
3            0  QA4   2.940000
4            0  QA5  11.620000
5            1  QA1   6.583333
6            1  QA2  10.555556
7            1  QA3  35.400000
8            1  QA4   4.428571
9            1  QA5  22.765957
10           2  QA1   7.740000
11           2  QA2  12.500000
12           2  QA3  58.612245
13           2  QA4   4.184211
14           2  QA5  33.083333
15           4  QA1  10.959184
16           4  QA2  15.883721
17           4  QA3  74.940000
18           4  QA4   4.204082
19           4  QA5  37.377778
20           8  QA1  14.346939
21           8  QA2  20.487179
22           8  QA3  98.020000
23           8  QA4   7.923077
24           8  QA5  38.562500
25          16  QA1  24.306122
26          16  QA2  22.227273
27          16  QA3  98.740000
28          16  QA4   9.697674
29          16  QA5  52.425532

In [52]:
visualization.create_line_chart(
    df=mean_rr_df,
    experiment_title="Recursive Retrieval Prompt Usage",
    x_axis='token_size',
    y_axis='prompt',
    category='QA',
    n_types=5,
    x_label='Token Size (Log$\mathregular{_2}$ Scale)',
    y_label = 'Mean Prompts Used', 
    x_lims=(0, 18),
    y_lims=(0, 110),
    y_grid=True,
    y_grid_minor=False,
)

<>:8: SyntaxWarning: invalid escape sequence '\m'
<>:8: SyntaxWarning: invalid escape sequence '\m'
/tmp/ipykernel_45025/125684509.py:8: SyntaxWarning: invalid escape sequence '\m'
  x_label='Token Size (Log$\mathregular{_2}$ Scale)',

In [53]:
mean_rr_df['Retrieval Strategy'] = 'Recursive Retrieval'
mean_rr_df

    token_size   QA     prompt   Retrieval Strategy
0            0  QA1   3.200000  Recursive Retrieval
1            0  QA2   4.265306  Recursive Retrieval
2            0  QA3  26.540000  Recursive Retrieval
3            0  QA4   2.940000  Recursive Retrieval
4            0  QA5  11.620000  Recursive Retrieval
5            1  QA1   6.583333  Recursive Retrieval
6            1  QA2  10.555556  Recursive Retrieval
7            1  QA3  35.400000  Recursive Retrieval
8            1  QA4   4.428571  Recursive Retrieval
9            1  QA5  22.765957  Recursive Retrieval
10           2  QA1   7.740000  Recursive Retrieval
11           2  QA2  12.500000  Recursive Retrieval
12           2  QA3  58.612245  Recursive Retrieval
13           2  QA4   4.184211  Recursive Retrieval
14           2  QA5  33.083333  Recursive Retrieval
15           4  QA1  10.959184  Recursive Retrieval
16           4  QA2  15.883721  Recursive Retrieval
17           4  QA3  74.940000  Recursive Retrieval
18           4  QA4   4.204082  Recursive Retrieval
19           4  QA5  37.377778  Recursive Retrieval
20           8  QA1  14.346939  Recursive Retrieval
21           8  QA2  20.487179  Recursive Retrieval
22           8  QA3  98.020000  Recursive Retrieval
23           8  QA4   7.923077  Recursive Retrieval
24           8  QA5  38.562500  Recursive Retrieval
25          16  QA1  24.306122  Recursive Retrieval
26          16  QA2  22.227273  Recursive Retrieval
27          16  QA3  98.740000  Recursive Retrieval
28          16  QA4   9.697674  Recursive Retrieval
29          16  QA5  52.425532  Recursive Retrieval

### ReES Mean Prompt Usage (up to 16k)

In [54]:
rees_dataset_path = Path("../main-accuracy/202506052215")
rees_dataset_path2 = Path("../main-accuracy/202506081025")
rees_dataset_path3 = Path("../main-accuracy/202506081359")

df1 = pd.read_csv(rees_dataset_path / Path("prompts-qa1.csv"))
df1["QA"] = "QA1"

df2 = pd.read_csv(rees_dataset_path / Path("prompts-qa2.csv"))
df2["QA"] = "QA2"

df3 = pd.read_csv(rees_dataset_path / Path("prompts-qa3.csv"))
df3["QA"] = "QA3"

df4 = pd.read_csv(rees_dataset_path / Path("prompts-qa4.csv"))
df4["QA"] = "QA4"

df5 = pd.read_csv(rees_dataset_path / Path("prompts-qa5.csv"))
df5["QA"] = "QA5"

df6 = pd.read_csv(rees_dataset_path2 / Path("prompts-qa1.csv"))
df6["QA"] = "QA1"

df7 = pd.read_csv(rees_dataset_path2 / Path("prompts-qa2.csv"))
df7["QA"] = "QA2"

df8 = pd.read_csv(rees_dataset_path2 / Path("prompts-qa3.csv"))
df8["QA"] = "QA3"

df9 = pd.read_csv(rees_dataset_path2 / Path("prompts-qa4.csv"))
df9["QA"] = "QA4"

df10 = pd.read_csv(rees_dataset_path2 / Path("prompts-qa5.csv"))
df10["QA"] = "QA5"

df11 = pd.read_csv(rees_dataset_path3 / Path("prompts-qa1.csv"))
df11["QA"] = "QA1"

df12 = pd.read_csv(rees_dataset_path3 / Path("prompts-qa2.csv"))
df12["QA"] = "QA2"

df13 = pd.read_csv(rees_dataset_path3 / Path("prompts-qa3.csv"))
df13["QA"] = "QA3"

df14 = pd.read_csv(rees_dataset_path3 / Path("prompts-qa4.csv"))
df14["QA"] = "QA4"

df15 = pd.read_csv(rees_dataset_path3 / Path("prompts-qa5.csv"))
df15["QA"] = "QA5"


rees_df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15])
rees_df

,token_size,index,prompt,response,llm_time,input_tokens,output_tokens,entity,QA
0,0,1,Daniel moved to the bathroom.,Daniel moved to the bathroom.,1.482202,161,6,daniel,QA1
1,0,1,<summary>\nDaniel moved to the bathroom.\n</su...,Bathroom,0.695651,76,1,NaN,QA1
2,0,2,Daniel moved to the kitchen and later journeye...,Daniel moved to the kitchen and later journeye...,0.867510,174,13,daniel,QA1
3,0,2,<summary>\nDaniel moved to the kitchen and lat...,Bedroom,0.539345,83,1,NaN,QA1
4,0,3,Daniel traveled to the office and the bathroom.,Daniel traveled to the office and the bathroom.,0.899141,159,9,daniel,QA1
...,...,...,...,...,...,...,...,...,...
2212,128,50,<summary>\n\n</summary>\n<chunk>\nJeff journey...,Jeff journeyed to the garden and is associated...,0.959794,238,35,jeff,QA5
2213,128,50,<summary>\nJeff journeyed to the garden and is...,"Jeff is associated with Gallatin and Paine, an...",1.412647,285,65,jeff,QA5
2214,128,50,<summary>\nJeff is associated with Gallatin an...,"Jeff is associated with Gallatin and Paine, an...",2.370635,396,100,jeff,QA5
2215,128,50,<summary>\nJeff is associated with Gallatin an...,"Jeff is associated with Gallatin and Paine, an...",2.406918,350,129,jeff,QA5
2216,128,50,<summary>\nMilk was obtained by Fred at a cert...,Uncle,0.442869,253,2,NaN,QA5

In [55]:
# Data format is same as Recursive Retrieval, so we take the same steps, except for truncating to 16k also
rees_df = rees_df[rees_df['entity'].notna()]
rees_df = rees_df[rees_df['token_size'] <= 16]
grouped_rees_df = rees_df.groupby(['token_size', 'index', 'QA'])['prompt'].count().reset_index()
mean_rees_df = grouped_rees_df.groupby(['token_size', 'QA'])["prompt"].mean().reset_index()
mean_rees_df

    token_size   QA     prompt
0            0  QA1   1.000000
1            0  QA2   1.142857
2            0  QA3   5.340000
3            0  QA4   1.000000
4            0  QA5   2.380000
5            1  QA1   2.312500
6            1  QA2   2.666667
7            1  QA3   8.000000
8            1  QA4   1.714286
9            1  QA5   6.127660
10           2  QA1   2.820000
11           2  QA2   2.694444
12           2  QA3   9.959184
13           2  QA4   1.684211
14           2  QA5  10.062500
15           4  QA1   2.673469
16           4  QA2   3.093023
17           4  QA3  10.700000
18           4  QA4   1.755102
19           4  QA5  11.311111
20           8  QA1   2.530612
21           8  QA2   3.846154
22           8  QA3  14.380000
23           8  QA4   2.153846
24           8  QA5   9.937500
25          16  QA1   3.489796
26          16  QA2   2.636364
27          16  QA3  12.920000
28          16  QA4   1.930233
29          16  QA5  11.489362

In [56]:
visualization.create_line_chart(
    df=mean_rees_df,
    experiment_title="Basic Retrieval Prompt Usage",
    x_axis='token_size',
    y_axis='prompt',
    category='QA',
    n_types=5,
    x_label='Token Size (Log$\mathregular{_2}$ Scale)',
    y_label = 'Mean Prompts Used', 
    x_lims=(0, 18),
    y_lims=(0, 110),
    # y_lims=None,
    y_grid=True,
    y_grid_minor=False,
)

<>:8: SyntaxWarning: invalid escape sequence '\m'
<>:8: SyntaxWarning: invalid escape sequence '\m'
/tmp/ipykernel_45025/2671590651.py:8: SyntaxWarning: invalid escape sequence '\m'
  x_label='Token Size (Log$\mathregular{_2}$ Scale)',

In [57]:
mean_rees_df['Retrieval Strategy'] = 'Basic Retrieval'
mean_rees_df

    token_size   QA     prompt Retrieval Strategy
0            0  QA1   1.000000    Basic Retrieval
1            0  QA2   1.142857    Basic Retrieval
2            0  QA3   5.340000    Basic Retrieval
3            0  QA4   1.000000    Basic Retrieval
4            0  QA5   2.380000    Basic Retrieval
5            1  QA1   2.312500    Basic Retrieval
6            1  QA2   2.666667    Basic Retrieval
7            1  QA3   8.000000    Basic Retrieval
8            1  QA4   1.714286    Basic Retrieval
9            1  QA5   6.127660    Basic Retrieval
10           2  QA1   2.820000    Basic Retrieval
11           2  QA2   2.694444    Basic Retrieval
12           2  QA3   9.959184    Basic Retrieval
13           2  QA4   1.684211    Basic Retrieval
14           2  QA5  10.062500    Basic Retrieval
15           4  QA1   2.673469    Basic Retrieval
16           4  QA2   3.093023    Basic Retrieval
17           4  QA3  10.700000    Basic Retrieval
18           4  QA4   1.755102    Basic Retrieval
19           4  QA5  11.311111    Basic Retrieval
20           8  QA1   2.530612    Basic Retrieval
21           8  QA2   3.846154    Basic Retrieval
22           8  QA3  14.380000    Basic Retrieval
23           8  QA4   2.153846    Basic Retrieval
24           8  QA5   9.937500    Basic Retrieval
25          16  QA1   3.489796    Basic Retrieval
26          16  QA2   2.636364    Basic Retrieval
27          16  QA3  12.920000    Basic Retrieval
28          16  QA4   1.930233    Basic Retrieval
29          16  QA5  11.489362    Basic Retrieval

### Grouping Recursive Retrieval and ReES data
We are technically moving into 'mean of means' instead of 'overall mean' territory here. But since we have equal amounts of texts for all QAs and token sizes, the values are the same

In [58]:
total_meaned_rr_df = mean_rr_df.groupby(['token_size', 'Retrieval Strategy'])['prompt'].mean().reset_index()
total_meaned_rr_df['QA'] = 'Mean over all QAs'
total_meaned_rr_df

   token_size   Retrieval Strategy     prompt                 QA
0           0  Recursive Retrieval   9.713061  Mean over all QAs
1           1  Recursive Retrieval  15.946684  Mean over all QAs
2           2  Recursive Retrieval  23.223958  Mean over all QAs
3           4  Recursive Retrieval  28.672953  Mean over all QAs
4           8  Recursive Retrieval  35.867939  Mean over all QAs
5          16  Recursive Retrieval  41.479320  Mean over all QAs

In [59]:
total_meaned_rees_df = mean_rees_df.groupby(['token_size', 'Retrieval Strategy'])['prompt'].mean().reset_index()
total_meaned_rees_df['QA'] = 'Mean over all QAs'
total_meaned_rees_df

   token_size Retrieval Strategy    prompt                 QA
0           0    Basic Retrieval  2.172571  Mean over all QAs
1           1    Basic Retrieval  4.164222  Mean over all QAs
2           2    Basic Retrieval  5.444068  Mean over all QAs
3           4    Basic Retrieval  5.906541  Mean over all QAs
4           8    Basic Retrieval  6.569622  Mean over all QAs
5          16    Basic Retrieval  6.493151  Mean over all QAs

In [60]:
mean_rr_qa3_df = mean_rr_df[mean_rr_df['QA'] == 'QA3']
mean_rr_qa3_df

    token_size   QA     prompt   Retrieval Strategy
2            0  QA3  26.540000  Recursive Retrieval
7            1  QA3  35.400000  Recursive Retrieval
12           2  QA3  58.612245  Recursive Retrieval
17           4  QA3  74.940000  Recursive Retrieval
22           8  QA3  98.020000  Recursive Retrieval
27          16  QA3  98.740000  Recursive Retrieval

In [61]:
mean_rr_qa5_df = mean_rr_df[mean_rr_df['QA'] == 'QA5']
mean_rr_qa5_df

    token_size   QA     prompt   Retrieval Strategy
4            0  QA5  11.620000  Recursive Retrieval
9            1  QA5  22.765957  Recursive Retrieval
14           2  QA5  33.083333  Recursive Retrieval
19           4  QA5  37.377778  Recursive Retrieval
24           8  QA5  38.562500  Recursive Retrieval
29          16  QA5  52.425532  Recursive Retrieval

In [62]:
mean_rees_qa3_df = mean_rees_df[mean_rees_df['QA'] == 'QA3']
mean_rees_qa3_df

    token_size   QA     prompt Retrieval Strategy
2            0  QA3   5.340000    Basic Retrieval
7            1  QA3   8.000000    Basic Retrieval
12           2  QA3   9.959184    Basic Retrieval
17           4  QA3  10.700000    Basic Retrieval
22           8  QA3  14.380000    Basic Retrieval
27          16  QA3  12.920000    Basic Retrieval

In [63]:
mean_rees_qa5_df = mean_rees_df[mean_rees_df['QA'] == 'QA5']
mean_rees_qa5_df

    token_size   QA     prompt Retrieval Strategy
4            0  QA5   2.380000    Basic Retrieval
9            1  QA5   6.127660    Basic Retrieval
14           2  QA5  10.062500    Basic Retrieval
19           4  QA5  11.311111    Basic Retrieval
24           8  QA5   9.937500    Basic Retrieval
29          16  QA5  11.489362    Basic Retrieval

In [64]:
concat_df = pd.concat([total_meaned_rr_df, mean_rr_qa3_df, mean_rr_qa5_df, total_meaned_rees_df, mean_rees_qa3_df, mean_rees_qa5_df]).reset_index()
concat_df

    index  token_size   Retrieval Strategy     prompt                 QA
0       0           0  Recursive Retrieval   9.713061  Mean over all QAs
1       1           1  Recursive Retrieval  15.946684  Mean over all QAs
2       2           2  Recursive Retrieval  23.223958  Mean over all QAs
3       3           4  Recursive Retrieval  28.672953  Mean over all QAs
4       4           8  Recursive Retrieval  35.867939  Mean over all QAs
5       5          16  Recursive Retrieval  41.479320  Mean over all QAs
6       2           0  Recursive Retrieval  26.540000                QA3
7       7           1  Recursive Retrieval  35.400000                QA3
8      12           2  Recursive Retrieval  58.612245                QA3
9      17           4  Recursive Retrieval  74.940000                QA3
10     22           8  Recursive Retrieval  98.020000                QA3
11     27          16  Recursive Retrieval  98.740000                QA3
12      4           0  Recursive Retrieval  11.620000                QA5
13      9           1  Recursive Retrieval  22.765957                QA5
14     14           2  Recursive Retrieval  33.083333                QA5
15     19           4  Recursive Retrieval  37.377778                QA5
16     24           8  Recursive Retrieval  38.562500                QA5
17     29          16  Recursive Retrieval  52.425532                QA5
18      0           0      Basic Retrieval   2.172571  Mean over all QAs
19      1           1      Basic Retrieval   4.164222  Mean over all QAs
20      2           2      Basic Retrieval   5.444068  Mean over all QAs
21      3           4      Basic Retrieval   5.906541  Mean over all QAs
22      4           8      Basic Retrieval   6.569622  Mean over all QAs
23      5          16      Basic Retrieval   6.493151  Mean over all QAs
24      2           0      Basic Retrieval   5.340000                QA3
25      7           1      Basic Retrieval   8.000000                QA3
26     12           2      Basic Retrieval   9.959184                QA3
27     17           4      Basic Retrieval  10.700000                QA3
28     22           8      Basic Retrieval  14.380000                QA3
29     27          16      Basic Retrieval  12.920000                QA3
30      4           0      Basic Retrieval   2.380000                QA5
31      9           1      Basic Retrieval   6.127660                QA5
32     14           2      Basic Retrieval  10.062500                QA5
33     19           4      Basic Retrieval  11.311111                QA5
34     24           8      Basic Retrieval   9.937500                QA5
35     29          16      Basic Retrieval  11.489362                QA5

This visualisation is a bit out of the norm, so we do not import, but make it from the bottom.

In [65]:
fig, ax = plt.subplots(figsize=(10, 6))
sns_plot = sns.lineplot(
    data=concat_df,
    x='token_size',
    y='prompt',
    hue='QA',
    palette=sns.color_palette('colorblind6', n_colors=3),
    style='Retrieval Strategy',
    markers = {
        "Recursive Retrieval": 'o',
        "Basic Retrieval": 'X'
    },
    markersize=7,
    linewidth=1,
    linestyle='-',
    errorbar=None,
    dashes=False
)

experiment_title = "Recursive Retrieval Prompt Usage Ablation Study"

plt.xlim(-0.15, 18)
plt.ylim(0, 110)
plt.xscale('symlog', base = 2)

ax.grid(True, which='major', axis='x', linestyle='-', linewidth=1)
ax.xaxis.set_major_locator(LogLocator(2))
xticks_major = plt.xticks(minor=False)[0]

xticks_major = [int(xtick) for xtick in xticks_major if (float(xtick) == 0 or float(xtick) >= 1)]
xticks_major = xticks_major[:-2]
xticks_major.insert(0, 0)

# # Generate xtick labels
xtick_labels = [f"{int(tick)}k" for tick in xticks_major]
plt.xticks(xticks_major, xtick_labels, minor=False)

handles, legend = sns_plot.get_legend_handles_labels()

#Overwrite legends to have 4 spaces indentation for subcategories
indented_legend_labels = [
    'Question Type',
    '    Mean over all QAs',
    '    QA3',
    '    QA5',
    'Retrieval Strategy',
    '    Recursive Retrieval',
    '    Basic Retrieval'
]
legend = plt.legend(handles, indented_legend_labels, fontsize = 14)

for text in legend.get_texts():
    if text.get_text().strip() in ["Question Type", "Retrieval Strategy"]:  # match supergroup names
        text.set_fontweight("bold")


# Remove top and right boxes
plt.gca().spines["top"].set_visible(False)
plt.gca().spines["right"].set_visible(False)
ax.spines['bottom'].set_position(('outward', 10))
plt.title(experiment_title, fontsize = 20, pad=20, weight=600)
plt.xlabel('Token Size (Log$\mathregular{_2}$ Scale)', fontsize = 20, labelpad=10)
plt.ylabel('Mean Prompt Usage', fontsize = 20, labelpad=10)
# plt.legend(loc='upper center', fontsize = 16, bbox_to_anchor=(0.5, 1.14), ncols=5, frameon=False)
plt.tick_params(axis='both', labelsize = 16)
plt.tight_layout()
plt.savefig(f"{experiment_title}-linechart.pdf")
plt.show()

<>:62: SyntaxWarning: invalid escape sequence '\m'
<>:62: SyntaxWarning: invalid escape sequence '\m'
/tmp/ipykernel_45025/3843950338.py:62: SyntaxWarning: invalid escape sequence '\m'
  plt.xlabel('Token Size (Log$\mathregular{_2}$ Scale)', fontsize = 20, labelpad=10)

# Mean of Mean experiments
To verify that our methodology above is sound

In [66]:
# Load RR data from files
path = Path("202506070756/")
path2 = Path("202506081353/")

df1 = pd.read_csv(path / Path("prompts-qa1.csv"))
df1["QA"] = "QA1"

df2 = pd.read_csv(path / Path("prompts-qa2.csv"))
df2["QA"] = "QA2"

df3 = pd.read_csv(path / Path("prompts-qa3.csv"))
df3["QA"] = "QA3"

df4 = pd.read_csv(path / Path("prompts-qa4.csv"))
df4["QA"] = "QA4"

df5 = pd.read_csv(path / Path("prompts-qa5.csv"))
df5["QA"] = "QA5"

df6 = pd.read_csv(path2 / Path("prompts-qa1.csv"))
df6["QA"] = "QA1"

df7 = pd.read_csv(path2 / Path("prompts-qa2.csv"))
df7["QA"] = "QA2"

df8 = pd.read_csv(path2 / Path("prompts-qa3.csv"))
df8["QA"] = "QA3"

df9 = pd.read_csv(path2 / Path("prompts-qa4.csv"))
df9["QA"] = "QA4"

df10 = pd.read_csv(path2 / Path("prompts-qa5.csv"))
df10["QA"] = "QA5"


rr_df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10])
rr_df

,token_size,index,prompt,response,llm_time,input_tokens,output_tokens,entity,QA
0,0,1,<summary>\n\n</summary>\n<chunk>\nDaniel moved...,Daniel moved to the bathroom.,1.412632,161,6,daniel,QA1
1,0,1,<summary>\n\n</summary>\n<chunk>\nDaniel moved...,Daniel moved to the bathroom.,0.956846,161,6,bathroom,QA1
2,0,1,<summary>\nDaniel moved to the bathroom.\n\nDa...,Bathroom,0.528347,82,1,NaN,QA1
3,0,2,<summary>\n\n</summary>\n<chunk>\nDaniel moved...,Daniel moved to the kitchen and later journeye...,0.784679,174,13,daniel,QA1
4,0,2,<summary>\n\n</summary>\n<chunk>\nDaniel moved...,"The kitchen is a location where Daniel, Sandra...",1.757220,174,57,kitchen,QA1
...,...,...,...,...,...,...,...,...,...
6208,16,50,<summary>\nSir William Gordon of Park was a di...,Sir William Gordon of Park was a distinguished...,5.341851,3118,587,gordon,QA5
6209,16,50,<summary>\nSir William Gordon of Park was a di...,Sir William Gordon of Park was a distinguished...,4.236797,820,638,gordon,QA5
6210,16,50,<summary>\nSir William Gordon of Park was a di...,Sir William Gordon of Park was a distinguished...,4.759015,837,683,gordon,QA5
6211,16,50,<summary>\nSir William Gordon of Park was a di...,Sir William Gordon of Park was a distinguished...,4.543019,875,732,gordon,QA5
6212,16,50,<summary>\nBill is a protective and authoritat...,Apple,0.536038,1570,1,NaN,QA5

In [67]:
rr_df = rr_df.groupby(['token_size', 'index', 'QA'])['prompt'].count().reset_index()
rr_df

      token_size  index   QA  prompt
0              0      1  QA1       3
1              0      1  QA2       5
2              0      1  QA3      65
3              0      1  QA4       4
4              0      1  QA5       7
...          ...    ...  ...     ...
1495          16     50  QA1       3
1496          16     50  QA2      71
1497          16     50  QA3      27
1498          16     50  QA4       3
1499          16     50  QA5      70

[1500 rows x 4 columns]

First we run mean of means

In [68]:
# Group by token_size, and question type
grouped_df = rr_df.groupby(['token_size', 'QA'])['prompt'].mean().reset_index()
grouped_df

    token_size   QA  prompt
0            0  QA1    4.20
1            0  QA2    5.18
2            0  QA3   27.54
3            0  QA4    3.94
4            0  QA5   12.62
5            1  QA1    7.32
6            1  QA2   10.50
7            1  QA3   36.40
8            1  QA4    4.72
9            1  QA5   22.40
10           2  QA1    8.74
11           2  QA2   10.00
12           2  QA3   58.44
13           2  QA4    4.18
14           2  QA5   32.76
15           4  QA1   11.74
16           4  QA2   14.66
17           4  QA3   75.94
18           4  QA4    5.12
19           4  QA5   34.64
20           8  QA1   15.06
21           8  QA2   16.98
22           8  QA3   99.02
23           8  QA4    7.18
24           8  QA5   38.02
25          16  QA1   24.82
26          16  QA2   20.56
27          16  QA3   99.74
28          16  QA4    9.34
29          16  QA5   50.28

In [69]:
# Now take overall mean
mean_of_means = grouped_df.groupby('token_size')['prompt'].mean()
mean_of_means

token_size
0     10.696
1     16.268
2     22.824
4     28.420
8     35.252
16    40.948
Name: prompt, dtype: float64

Now we look at the overall mean

In [70]:
overall_mean = rr_df.groupby(['token_size'])['prompt'].mean()
overall_mean

token_size
0     10.696
1     16.268
2     22.824
4     28.420
8     35.252
16    40.948
Name: prompt, dtype: float64

We conclude that mean of means and overall mean is identical here, so our earlier analysis should be correct.